# -*- coding: utf-8 -*-
"""run_e2e_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9R1SQPX-SSvSS-NuimK5E4o69eKF2S3
"""

import os
os.chdir("/content")

# Git Clone if needed
if not os.path.exists("/content/AAI-590-Capstone-group2"):
    os.system("git clone https://github.com/TEJSINGH17/AAI-590-Capstone-group2.git /content/AAI-590-Capstone-group2")
    print("Repo cloned")
else:
    print("Repo exists")

# Install deps
os.system("pip install ultralytics opencv-python-headless imageio imageio-ffmpeg -q")
print("Dependencies ready")

# Check JSON
json_dir = "/content/AAI-590-Capstone-group2/runs/hud/ds_1"
n = len([f for f in os.listdir(json_dir) if f.endswith('.json')]) if os.path.exists(json_dir) else 0
print(f"{'##' if n>0 else 'X'} JSON files: {n}")

# Check video
video = "/content/AAI-590-Capstone-group2/output_ds_1.mp4"
size = os.path.getsize(video)/1e6 if os.path.exists(video) else 0
print(f"{'##' if size>1 else 'Not Done'} Video: {size:.1f} MB")

print("\n Setup done!")

#Upload mp4 videos from your drive
import os, shutil
from google.colab import files

print("Please select output_ds_1.mp4 from your computer...")
uploaded = files.upload()

for fname in uploaded.keys():
    dest = f"/content/AAI-590-Capstone-group2/{fname}"
    shutil.move(fname, dest)
    size = os.path.getsize(dest)/1e6
    print(f"{'Done' if size>1 else 'Not Done'} {fname}: {size:.1f} MB")

import ipywidgets as widgets
from IPython.display import display

mode_selector = widgets.RadioButtons(
    options=[
        ('Mode 1 — File Mode  (JSON → HUD, no Jetson needed)', 'file'),
        ('Mode 2 — UDP Live   (Victor pipeline → HUD, no Jetson needed)', 'udp'),
        ('Mode 3 — Jetson     (DeepStream → HUD, Jetson required)', 'jetson'),
    ],
    value='file',
    description='',
    layout=widgets.Layout(width='600px')
)

print("="*60)
print("  OmniView AI — Select Pipeline Mode")
print("="*60)
display(mode_selector)
print("\nAfter selecting mode, run next cell")

import os
os.chdir("/content")

MODE  = mode_selector.value
REPO  = "/content/AAI-590-Capstone-group2"
VIDEO = f"{REPO}/output_ds_1.mp4"
JSON  = f"{REPO}/runs/hud/ds_1"

print(f"Running: {MODE.upper()} mode\n")

if MODE == "file":
    !python3 /content/AAI-590-Capstone-group2/omniview_e2e_live.py \
        --no-bootstrap \
        --mode file \
        --json /content/AAI-590-Capstone-group2/runs/hud/ds_1 \
        --video /content/AAI-590-Capstone-group2/output_ds_1.mp4 \
        --output /content/omniview_live_hud.mp4 \
        --gif-frames 300 \
        --gif-fps 10

elif MODE == "udp":
    print("Starting UDP mode...")

elif MODE == "jetson":
    print("Jetson required for Mode 3")

from IPython.display import Image, display
import os

gif = "/content/omniview_live_hud.gif"
if os.path.exists(gif):
    size = os.path.getsize(gif)/1e6
    print(f"GIF: {size:.1f} MB  (30 seconds)")
    display(Image(filename=gif))
else:
    print("GIF not found yet")