# -*- coding: utf-8 -*-
"""run_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P06yi_gzgqFG2CJrehI-bao1SlE19NWe
"""

import os
os.chdir("/content")
print(os.getcwd())

import os
os.chdir("/content")
os.makedirs("/content/AAI-590-Capstone-group2/test_data", exist_ok=True)

from google.colab import files
uploaded = files.upload()  # select output_ds_1.mp4

import shutil
for fname in uploaded.keys():
    shutil.move(fname, f"/content/AAI-590-Capstone-group2/test_data/{fname}")
    print(f"Done! Moved {fname}")

import os
test_data = "/content/AAI-590-Capstone-group2/test_data"
if os.path.exists(test_data):
    files = os.listdir(test_data)
    print(f"Files in test_data/: {files}")
    for f in files:
        size = os.path.getsize(os.path.join(test_data, f))
        print(f"  {f}: {size/1e6:.1f} MB")
else:
    print("test_data/ folder does not exist!")

import os
path = "/content/AAI-590-Capstone-group2/test_data/output_ds_1.mp4"
exists = os.path.exists(path)
size = os.path.getsize(path) if exists else 0
print(f"Exists: {exists}")
print(f"Size: {size/1e6:.1f} MB")

import os
os.makedirs("/content/AAI-590-Capstone-group2/test_data", exist_ok=True)

from google.colab import files
print("Please select output_ds_1.mp4 from your computer...")
uploaded = files.upload()

import shutil
for fname in uploaded.keys():
    dest = f"/content/AAI-590-Capstone-group2/test_data/{fname}"
    shutil.move(fname, dest)
    size = os.path.getsize(dest)
    print(f"Uploaded: {fname} ({size/1e6:.1f} MB)")

#second rerun
import os
os.chdir("/content")

!python3 /content/omniview_e2e_live.py \
    --no-bootstrap \
    --mode file \
    --json /content/AAI-590-Capstone-group2/runs/hud/ds_1 \
    --video /content/AAI-590-Capstone-group2/test_data/output_ds_1.mp4 \
    --output /content/omniview_live_hud.mp4 \
    --gif-frames 40 \
    --gif-fps 10

from IPython.display import Image, display
display(Image(filename="/content/omniview_live_hud.gif"))